$file = "src/views/Etudiant/LettresRecommandation.vue"
$content = Get-Content $file -Raw -Encoding UTF8

$content = $content.Replace('GÃ©rez', 'Gérez')
$content = $content.Replace('reÃ§ues', 'reçues')
$content = $content.Replace('REÃ‡UES', 'REÇUES')
$content = $content.Replace('DIFFÃ‰RENTS', 'DIFFÉRENTS')
$content = $content.Replace('reÃ§ue', 'reçue')
$content = $content.Replace('rÃ©digÃ©es', 'rédigées')
$content = $content.Replace('apparaÃ®tront', 'apparaîtront')
$content = $content.Replace('ReÃ§ue', 'Reçue')
$content = $content.Replace('TÃ©lÃ©charger', 'Télécharger')
$content = $content.Replace('reÃ§u', 'reçu')
$content = $content.Replace('RÃ©partition', 'Répartition')
$content = $content.Replace('DÃ©crivez', 'Décrivez')
$content = $content.Replace('VisibilitÃ©', 'Visibilité')
$content = $content.Replace('PrivÃ©e', 'Privée')
$content = $content.Replace('TÃ©lÃ©chargeable', 'Téléchargeable')
$content = $content.Replace('UniversitÃ©', 'Université')
$content = $content.Replace('succÃ¨s', 'succès')
$content = $content.Replace('envoyÃ©e', 'envoyée')
$content = $content.Replace('ingÃ©nieur', 'ingénieur')
$content = $content.Replace('Ã©tÃ©', 'été')
$content = $content.Replace('diplÃ´me', 'diplôme')
$content = $content.Replace('caractÃ¨res', 'caractères')
$content = $content.Replace('dÃ©passer', 'dépasser')
$content = $content.Replace('adressÃ©e', 'adressée')
$content = $content.Replace('ENSAâ€"', 'ENSA—')
$content = $content.Replace('Ã©', 'é')
$content = $content.Replace('Ã ', 'à')
$content = $content.Replace('Ã¨', 'è')
$content = $content.Replace('Ã®', 'î')
$content = $content.Replace('Ã´', 'ô')
$content = $content.Replace('Ã§', 'ç')
$content = $content.Replace('â€"', '—')
$content = $content.Replace('â†"', '↓')

$content | Set-Content $file -Encoding UTF8 -NoNewline
Write-Host "Done."
