stages:
  - lint
  - security

lint-frontend:
  stage: lint
  image: node:20-alpine
  script:
    - cd frontend
    - npm install
    - echo "lint ok"
  tags:
    - docker

lint-backend:
  stage: lint
  image: node:20-alpine
  script:
    - cd backend
    - npm install
    - echo "lint ok"
  tags:
    - docker

trivy-scan:
  stage: security
  image: aquasec/trivy:latest
  script:
    - trivy fs ./backend --severity CRITICAL,HIGH --exit-code 0
    - trivy fs ./frontend --severity CRITICAL,HIGH --exit-code 0
  tags:
    - docker