[vm_chef]
192.168.20.10 ansible_user=aya ansible_password=aya123 ansible_become_password=aya123

[vm_adjoint]
192.168.20.11 ansible_user=aya ansible_password=aya123 ansible_become_password=aya123

[vm_chef_db]
192.168.20.12 ansible_user=aya ansible_password=aya123 ansible_become_password=aya123

[vm_adjoint_db]
192.168.20.13 ansible_user=aya ansible_password=aya123 ansible_become_password=aya123

[all_vms:children]
vm_chef
vm_adjoint
vm_chef_db
vm_adjoint_db
