---
- name: Configure staging server
  hosts: staging
  become: true
  roles:
    - docker
    - app
    - monitoring

- name: Configure prod server
  hosts: prod
  become: true
  roles:
    - app
    - monitoring