name: CD — Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          target: production
          push: true
          tags: aymenbazga/trusty-frontend:latest
          build-args: |
            VITE_API_URL=http://63.183.184.130

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          target: production
          push: true
          tags: aymenbazga/trusty-backend:latest

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to staging via SSH
        if: github.event_name == 'push' && (github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/mirroring' || github.ref == 'refs/heads/devloppement')
        continue-on-error: true
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ubuntu
          key: ${{ secrets.STAGING_DEPLOY_KEY }}
          script: |
            cd /home/ubuntu/projet/Trusty
            docker pull aymenbazga/trusty-frontend:latest
            docker pull aymenbazga/trusty-backend:latest
            docker pull aymenbazga/trusty-nginx:latest
            docker compose -f docker-compose.dockerhub.yml \
              --env-file .env.staging \
              up -d --force-recreate
            docker exec trusty-backend-1 npx prisma migrate deploy
